// <auto-generated />
namespace Webapp2_Oblig1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initialconfig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialconfig));
        
        string IMigrationMetadata.Id
        {
            get { return "201509041250401_initial config"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
